config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
        resources :jobs do
            member do
                post :publish
                post :hide
            end
            resources :resumes
        end
    end

    devise_for :users

    resources :groups do
        member do
            post :join
            post :quit
        end
        resources :posts
    end

    namespace :account do
      resources :groups
      resources :posts
    end

    resources :jobs do
        resources :resumes
    end
    root 'welcome#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    scope :published, -> { where(is_hidden: false) }
    scope :recent, -> { order('created_at DESC') }
    validates :title, presence: true
    validates :wage_upper_bound, presence: true
    validates :wage_lower_bound, presence: true
    validates :wage_lower_bound, numericality: { greater_than: 0}

    has_many :resumes

    def publish!
      self.is_hidden = false
      self.save
    end

    def hide!
      self.is_hidden = true
      self.save
    end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This Job already archieved"
      redirect_to root_path
    end
  end

  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end
  end


  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end

  def job_coll_edit(job)
      content_tag(:span, "", :class => "fa fa-pencil")
  end

  def job_coll_Destroy(job)
      content_tag(:span, "", :class => "fa fa-trash-o")
  end

  def job_coll_see(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-eye")
    else
      content_tag(:span, "", :class => "fa fa-eye-slash")
    end
  end




end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("新 增 职 位", new_admin_job_path, :class => "btn btn-default" ) %>
</div>

<br><br>

<table class="table table-boldered table-striped custab" >
    <thead>
        <tr>
            <td>
                招募职位
            </td>

            <td>
              收到履历
            </td>
            <td>
                薪资下限
            </td>
            <td>
                薪资上限
            </td>
            <td>
                管理选项
            </td>
            <td>
                发布时间
            </td>
        </tr>
    </thead>

    <% @jobs.each do |job| %>
    <tr>

        <td>
            <%= render_job_status(job) %>

            <%= link_to(job.title, admin_job_path(job)) %>
        </td>
        <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
        <td> <%= job.wage_lower_bound %> </td>
        <td> <%= job.wage_upper_bound %> </td>
        <td>
            <%= link_to(job_coll_edit(job), edit_admin_job_path(job), :class => "btn btn-xs btn-info") %>
            <%= link_to(job_coll_Destroy(job), admin_job_path(job), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure?" }) %>
            <% if job.is_hidden %>

            <%= link_to(job_coll_see(job), publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success") %>
        <% else %>
            <%= link_to(job_coll_see(job), hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning") %>
            <% end %>
        </td>
        <td>
            <%= job.created_at %>
        </td>
    </tr>
    <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>