config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
        resources :jobs do
            member do
                post :publish
                post :hide
            end
            resources :resumes
        end
    end

    devise_for :users

    resources :groups do
        member do
            post :join
            post :quit
        end
        resources :posts
    end

    namespace :account do
      resources :groups
      resources :posts
    end

    resources :jobs do
        resources :resumes
    end
    root 'welcome#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :posts
 validates :title, presence: true

 has_many :group_relationships
 has_many :members, through: :group_relationships, source: :user
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
    scope :published, -> { where(is_hidden: false) }
    scope :recent, -> { order('created_at DESC') }
    validates :title, presence: true
    validates :wage_upper_bound, presence: true
    validates :wage_lower_bound, presence: true
    validates :wage_lower_bound, numericality: { greater_than: 0}

    has_many :resumes

    def publish!
      self.is_hidden = false
      self.save
    end

    def hide!
      self.is_hidden = true
      self.save
    end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC")}
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true


end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :resumes
    has_many :groups
    has_many :posts

    def is_member_of?(group)
        participated_groups.include?(group)
    end

    has_many :group_relationships
    has_many :participated_groups, through: :group_relationships, source: :group

    def admin?
        is_admin
    end

      def join!(group)
        participated_groups << group
      end

      def quit!(group)
        participated_groups.delete(group)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

    def index
        @groups = current_user.participated_groups
    end

    def new
      @group = Group.new
    end

    def show
      @group = Group.find(params[:id])
      @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5)
    end

    def edit
    end

    def create
      @group = Group.new(group_params)
      @group.user = current_user

      if @group.save
        current_user.join!(@group)
        redirect_to groups_path
      else
        render :new
      end
    end

    def update
      if @group.update(group_params)
        redirect_to groups_path, notice: "Update Success"
      else
        render :edit
      end
    end

    def destroy
      @group.destroy
      redirect_to groups_path, alert: "Group deleted"
    end

       def join
        @group = Group.find(params[:id])

         if !current_user.is_member_of?(@group)
           current_user.join!(@group)
           flash[:notice] = "加入本讨论版成功！"
         else
           flash[:warning] = "你已经是本讨论版成员了！"
         end

         redirect_to group_path(@group)
       end

       def quit
         @group = Group.find(params[:id])

         if current_user.is_member_of?(@group)
           current_user.quit!(@group)
           flash[:alert] = "已退出本讨论版！"
         else
           flash[:warning] = "你不是本讨论版成员，怎么退出 XD"
         end

         redirect_to group_path(@group)
       end

    private

    def find_group_and_check_permission
      @group = Group.find(params[:id])

      if current_user != @group.user
        redirect_to root_path, alert: "You have no permission."
      end
    end

    def group_params
        params.require(:group).permit(:title, :description)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This Job already archieved"
      redirect_to root_path
    end
  end

  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end
  end


  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create]

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
  end

  def index
    @posts = current_user.posts
  end


  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end


  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end

  def job_coll_edit(job)
      content_tag(:span, "", :class => "fa fa-pencil")
  end

  def job_coll_Destroy(job)
      content_tag(:span, "", :class => "fa fa-trash-o")
  end

  def job_coll_see(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-eye")
    else
      content_tag(:span, "", :class => "fa fa-eye-slash")
    end
  end




end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 职人聚合所
        <br>Design by Joshuagou

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"> 职人聚合所 </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                 <% if !current_user %>
                   <li><%= link_to("注册", new_user_registration_path) %> </li>
                   <li><%= link_to("登入", new_user_session_path) %></li>
                 <% else %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Hi!, <%= current_user.email %>
                         <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                         <% if current_user.admin? %>
                         <li> <%= link_to("My Groups", account_groups_path) %></li>
                         <li> <%= link_to("My Posts", account_posts_path) %></li>
                         <li class="divider"> </li>
                         <li> <%= link_to("管理发布的职位", admin_jobs_path) %> </li>
                         <% end %>
                         <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                     </ul>
                   </li>
                 <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Job Listing </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <div class="row">
              <div class="col-md-2">

                <ul class="nav nav-pills nav-stacked" style="max-width: 200px; padding-top:20px;">
                   <li class="active"><%= link_to("职 位 仓 库", admin_jobs_path ) %> </li>
                </ul>

              </div>

              <div class="col-md-10">
                <%= yield %>
              </div>
           </div>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobmo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
    </div>

    <%= render "common/footer" %>
  </body>
</html>